# Generated by Django 3.2 on 2021-05-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_phone', models.CharField(max_length=20)),
                ('c_fname', models.CharField(max_length=128)),
                ('c_lname', models.CharField(max_length=128)),
                ('c_address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=128)),
                ('d_percent', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.FloatField(default=0)),
                ('order_date', models.DateField()),
                ('delivery_mode', models.CharField(choices=[('pick-up', 'Pick Up'), ('home-delivery', 'Home Delivery')], max_length=128)),
                ('feedback', models.CharField(default='NULL', max_length=128)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakerystore.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=128)),
                ('p_price', models.FloatField(default=0)),
                ('p_descp', models.CharField(default='NULL', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=128)),
                ('s_phone', models.CharField(max_length=10)),
                ('s_address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('g', 'g'), ('l', 'litres'), ('#', '#')], max_length=128)),
                ('quantity', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakerystore.item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakerystore.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ol_unit', models.IntegerField(default=1)),
                ('ol_cost', models.FloatField(default=0)),
                ('ol_exp_date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakerystore.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakerystore.product')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('receive_date', models.DateField()),
                ('invoice_amount', models.FloatField()),
                ('invoice_num', models.CharField(max_length=128)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakerystore.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='HomeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hd_address', models.CharField(max_length=128)),
                ('hd_date', models.DateField()),
                ('hd_time', models.TimeField()),
                ('hd_instruction', models.CharField(max_length=128)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakerystore.order')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('extra_charge', models.FloatField(default=0)),
                ('bill_amt', models.FloatField(default=0)),
                ('bill_discount_amount', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('pay_mode', models.CharField(max_length=128)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakerystore.discount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakerystore.order')),
            ],
        ),
    ]
