# Generated by Django 3.2 on 2021-05-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakerystore', '0003_invoice_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='status',
            new_name='invoice_status',
        ),
    ]
