# Generated by Django 3.2 on 2021-06-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakerystore', '0005_customer_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
