# Generated by Django 3.2 on 2021-06-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakerystore', '0006_alter_customer_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='created',
            field=models.DateField(default='2021-04-01'),
        ),
    ]
