# Generated by Django 3.2 on 2021-06-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakerystore', '0007_orderlist_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
